spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useSSL=false

  session:
    store-type: none


#security:
#  basic:
#    enabled: true

#应用级配置
earthchen:
  security:
    #    browser:
    ##      配置自定义登录页,不配置则为默认登录页
    #      loginPage: /demo-signIn.html

    validateCode:
      imageCode:
        #         设置图形验证码的长度为6，不配置则为默认验证码属性
        length: 6
        width: 100
        url: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret:
        # 设置providerId
        providerId: callback.do
        # 将社交登录social前缀的/auth改为以下内容

      filterProcessesUrl: /social-auth

