spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useSSL=false

  session:
    store-type: none


#security:
#  basic:
#    enabled: true

#应用级配置
earthchen:
  security:
    browser:
      ##      配置自定义登录页,不配置则为默认登录页
      #      loginPage: /demo-signIn.html
      # 配置自定义注册页
      registerPage: /demo-signUp.html

#    validateCode:
#      imageCode:
#        #         设置图形验证码的长度为6，不配置则为默认验证码属性
#        length: 6
#        width: 100
#        url: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret:
        # 设置providerId
        providerId: callback.do
        # 将社交登录social前缀的/auth改为以下内容
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /social-auth

server:
  session:
    #  设置session超时时间(最小是1分钟 )
    timeout: 600

security:
  oauth2:
    client:
      client-id: earthchen
      client-secret: earthchensecret
      registered-redirect-uri: "http://example.com"
