spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 960921
    username: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo

  session:
    store-type: none


#security:
#  basic:
#    enabled: true

#应用级配置
#zcq:
#  security:
#    browser:
##      配置自定义登录页,不配置则为默认登录页
#      loginPage: /demo-signIn.html


